### ISSUE TITLE
Question: Any plans to translate the manual of Getsu Fuuma Den?

### ISSUE THREAD

**Issue by TsukiZero** [celcion/NebulousTranslations#1]
Now that the manual is digitally available with the downloaded game, all that it needs is a translation.

**Comment by celcion** [comment]
Hello! Sorry for the late answer. No, we don't have such plans. We had the manual itself even back then, but it was pretty hard to translate it without completely redesigning the pages (it was optimized for vertical text alignment). We decided it's not really worth the effort.
